/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package util;

import java.io.Serializable;

/**
 *
 * @author student1
 */
public enum ResponseStatus implements Serializable{
    SUCCESS,
    SUCCESS_LOGIN,
    ERROR,
    SUCCESS_LOGOUT_MENADZER,
    FAIL_LOGIN,
    SUCCESS_SAVE_MENADZER,
    SUCCESS_GET_ALL_VRSTAIZVODJACA,
    ERROR_SAVE_MENADZER, ERROR_SAVE_IZVODJAC,
    SUCCESS_SAVE_IZVODJAC,
    SUCCESS_PRETRAZIVANJE_PO_KRITERIJUMU, 
    ERROR_PRETRAZIVANJE_PO_KRITERIJUMU,
    SUCCESS_UCITAJ_IZVODJACA,
    ERROR_UCITAJ_IZVODJACA,
    SUCCESS_UPDATE_IZVODJACA,
    ERROR_UPDATE_IZVODJACA,
    SUCCESS_UCITAJ_LISTU_IZVODJACA,
    ERROR_UCITAJ_LISTU_IZVODJACA,
    SUCCESS_ZAPAMTI_BEND,
    ERROR_ZAPAMTI_BEND,
    SUCCESS_PRETRAZIVANJE_PO_KRITERIJUMU_BEND,
    ERROR_PRETRAZIVANJE_PO_KRITERIJUMU_BEND,
    SUCCESS_UCITAJ_BEND,
    ERROR_UCITAJ_BEND,
    SUCCESS_UPDATE_BEND,
    ERROR_UPDATE_BEND,
    SUCCESS_UCITAJ_LISTU_BENDOVA,
    ERROR_UCITAJ_LISTU_BENDOVA,
    SUCCESS_ZAPAMTI_NASTUP,
    ERROR_ZAPAMTI_NASTUP,
    SUCCESS_PRETRAZIVANJE_PO_KRITERIJUMU_NASTUP,
    ERROR_PRETRAZIVANJE_PO_KRITERIJUMU_NASTUP,
    SUCCESS_UCITAJ_NASTUP,
    ERROR_UCITAJ_NASTUP,
    SUCCESS_UPDATE_NASTUP,
    ERROR_UPDATE_NASTUP
}
